/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import restbucks.rest.impl.PermittedActions;
import restbucks.rest.serving.ServingResource;


@Service
public class OrderControllerSupport {

  public ResponseEntity<Void> delete(String orderId) {
    return new ResponseEntity<Void>(HttpStatus.NO_CONTENT);
  }

  public PermittedActions<ServingResource> get(String orderId) {
    ServingResource result = new ServingResource();
    // result.setXxx();
    PermittedActions<ServingResource> permittedActions = new PermittedActions<ServingResource>(result);
    // permittedActions.exclude(Actions.YYY);
    return permittedActions;
  }

  public PermittedActions<OrderResource> put(String orderId, OrderResource input) {
    OrderResource result = new OrderResource();
    // result.setXxx();
    PermittedActions<OrderResource> permittedActions = new PermittedActions<OrderResource>(result);
    // permittedActions.exclude(Actions.YYY);
    return permittedActions;
  }

}
