/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;


@Service
public class OrderService {

  public void delete() {
    // TODO: Implement
  }

  public Object put(Object input) {
    return null; // TODO: Implement
  }

  public Object get() {
    return null; // TODO: Implement
  }

}
