/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;


@Service
public class OrdersControllerHelper {

  public OrderDto post(OrderDto input) {
    return null; // TODO: Implement
  }

}
