/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;


@Service
public class OrdersService {

  public Object post(Object input) {
    return null; // TODO: Implement
  }

}
