/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;
import restbucks.rest.serving.ServingDto;


@Service
public class OrderControllerHelper {

  public void delete() {
    // TODO: Implement
  }

  public OrderDto put(OrderDto input) {
    return null; // TODO: Implement
  }

  public ServingDto get() {
    return null; // TODO: Implement
  }

}
