/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;
import restbucks.rest.serving.ServingDto;


@Service
public class OrderControllerHelper {

  public void delete() {
    // TODO: Implement
  }

  public ServingDto get() {
    return new ServingDto(); // TODO: Implement
  }

  public OrderDto put(OrderDto input) {
    return new OrderDto(); // TODO: Implement
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true; // TODO: Implement
  }

}
