/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;


@Service
public class OrdersControllerHelper {

  public OrderResource post(OrderResource input) {
    return new OrderResource(); // TODO: Implement
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true;// TODO: Implement
  }

}
