/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;
import restbucks.rest.serving.ServingResource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;


@Service
public class OrderControllerHelper {

  public ResponseEntity<Void> delete() {
    return new ResponseEntity<Void>(HttpStatus.NO_CONTENT); // TODO: Implement
  }

  public ServingResource get() {
    return new ServingResource(); // TODO: Implement
  }

  public OrderResource put(OrderResource input) {
    return new OrderResource(); // TODO: Implement
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true;// TODO: Implement
  }

}
