/*
 * Generated by RADL.
 */
package restbucks.rest.order;

import org.springframework.stereotype.Service;


@Service
public class OrdersControllerHelper {

  public OrderDto post(OrderDto input) {
    return new OrderDto(); // TODO: Implement
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true; // TODO: Implement
  }

}
