/*
 * Generated by RADL.
 */
package restbucks.rest.server.home;

import org.springframework.stereotype.Service;

import restbucks.rest.server.impl.ServiceUnavailableException;


@Service
public class HomeService {

  public Object get() {
    throw new ServiceUnavailableException();
  }

}
