/*
 * Generated by RADL.
 */
package restbucks.rest.server.home;

import org.springframework.stereotype.Service;


@Service
public class HomeService {

  public Object get() {
    return null; // TODO: Implement
  }

}
