/*
 * Generated by RADL.
 */
package restbucks.rest.menu;

import org.springframework.stereotype.Service;


@Service
public class MenuControllerHelper {

  public MenuDto get() {
    return null; // TODO: Implement
  }

}
