/*
 * Generated by RADL.
 */
package restbucks.rest.menu;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import restbucks.domain.menu.Drink;
import restbucks.domain.menu.DrinkRepository;
import restbucks.domain.menu.MenuItem;
import restbucks.rest.item.ItemResource;


@Service
public class MenuControllerHelper {

  @Autowired
  private DrinkRepository drinks;

  public MenuResource get() {
    MenuResource result = new MenuResource();
    Collection<ItemResource> items = new ArrayList<>();
    Locale locale = Locale.getDefault();
    for (Drink drink : drinks.findAll()) {
      for (MenuItem menuItem : MenuItem.variationsOf(drink)) {
        ItemResource item = new ItemResource();
        item.name = menuItem.getDrink().getName();
        item.size = menuItem.getSize().toString().toLowerCase(locale);
        item.milk = menuItem.getMilk().toString().toLowerCase(locale);
        item.price = menuItem.getDrink().getPrice();
        item.currency = menuItem.getDrink().getCurrency().getDisplayName(locale);
        items.add(item);
      }
    }
    result.item = items.toArray(new ItemResource[items.size()]);
    return result;
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true;
  }

}
