/*
 * Generated by RADL.
 */
package restbucks.rest.server.menu;

import org.springframework.stereotype.Service;


@Service
public class MenuService {

  public Object get() {
    return null; // TODO: Implement
  }

}
