/*
 * Generated by RADL.
 */
package restbucks.rest.home;

import org.springframework.stereotype.Service;

import restbucks.rest.impl.PermittedActions;


@Service
public class HomeControllerSupport {

  public PermittedActions<HomeResource> get() {
    return new PermittedActions<HomeResource>(new HomeResource());
  }

}
