/*
 * Generated by RADL.
 */
package restbucks.rest.home;

import org.springframework.stereotype.Service;

import restbucks.rest.impl.RestResponse;


@Service
public class HomeControllerSupport {

  public RestResponse<HomeResource> get() {
    return new RestResponse<HomeResource>(new HomeResource());
  }

}
