/*
 * Generated by RADL.
 */
package restbucks.rest.home;

import org.springframework.stereotype.Service;


@Service
public class HomeService {

  public Object get() {
    return new HomeDto(); // TODO: Implement
  }

}
