/*
 * Generated by RADL.
 */
package restbucks.rest.home;

import org.springframework.stereotype.Service;


@Service
public class HomeControllerHelper {

  public HomeResource get() {
    return new HomeResource(); // TODO: Implement
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true;// TODO: Implement
  }

}
