/*
 * Generated by RADL.
 */
package restbucks.rest.server.serving;

import org.springframework.stereotype.Service;


@Service
public class ServingService {

  public Object get() {
    return null; // TODO: Implement
  }

  public void delete() {
    // TODO: Implement
  }

}
