/*
 * Generated by RADL.
 */
package restbucks.rest.serving;

import org.springframework.stereotype.Service;


@Service
public class ServingControllerHelper {

  public ServingDto get() {
    return null; // TODO: Implement
  }

  public void delete() {
    // TODO: Implement
  }

}
