/*
 * Generated by RADL.
 */
package restbucks.rest.serving;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import restbucks.rest.impl.RestResponse;


@Service
public class ServingControllerSupport {

  public ResponseEntity<Void> delete(String orderId) {
    return new ResponseEntity<Void>(HttpStatus.NO_CONTENT);
  }

  public RestResponse<ServingResource> get(String orderId) {
    ServingResource result = new ServingResource();
    // result.setXxx();
    RestResponse<ServingResource> RestResponse = new RestResponse<ServingResource>(result);
    // RestResponse.exclude(Actions.YYY);
    return RestResponse;
  }

}
