/*
 * Generated by RADL.
 */
package restbucks.rest.payment;

import org.springframework.stereotype.Service;
import restbucks.rest.receipt.ReceiptResource;


@Service
public class PaymentsControllerHelper {

  public ReceiptResource post(PaymentResource input) {
    return new ReceiptResource(); // TODO: Implement
  }

  public boolean isLinkEnabled(String linkRelation) {
    return true;// TODO: Implement
  }

}
