/*
 * Generated by RADL.
 */
package restbucks.rest.payment;

import org.springframework.stereotype.Service;


@Service
public class PaymentsService {

  public Object post(Object input) {
    return null; // TODO: Implement
  }

}
