/*
 * Generated by RADL.
 */
package restbucks.rest.payment;

import org.springframework.stereotype.Service;
import restbucks.rest.receipt.ReceiptDto;


@Service
public class PaymentsControllerHelper {

  public ReceiptDto post(PaymentDto input) {
    return null; // TODO: Implement
  }

}
