/*
 * Generated by RADL.
 */
package restbucks.rest.payment;

import org.springframework.stereotype.Service;

import restbucks.rest.impl.RestResponse;
import restbucks.rest.receipt.ReceiptResource;


@Service
public class PaymentsControllerSupport {

  public RestResponse<ReceiptResource> post(String orderId, PaymentResource input) {
    ReceiptResource result = new ReceiptResource();
    // result.setXxx();
    RestResponse<ReceiptResource> RestResponse = new RestResponse<ReceiptResource>(result);
    // RestResponse.exclude(Actions.YYY);
    return RestResponse;
  }

}
